categories/urls.py
from django.urls import path

from . import views

app_name = 'categories'

urlpatterns = [
    path('category/<slug:slug>/',
         views.CategoryView.as_view(), name='category-detail'),
    path('create/',
         views.CreateCategoryView.as_view(), name='create-category'),
    path('update/<slug:slug>/',
         views.UpdateCategoryView.as_view(), name='update-category'),
    path('delete/<slug:slug>/',
         views.DeleteCategoryView.as_view(), name='delete-category'),
]

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('page/<slug:slug>/', views.PageView.as_view(), name='page-detail'),
    path('shared/<str:username>/<slug:slug>/',
         views.SharedPageView.as_view(), name='shared-page'),
    path('create/', views.CreatePageView.as_view(), name='create-page'),
    path('update/<slug:slug>/',
         views.UpdatePageView.as_view(), name='update-page'),
    path('delete/<slug:slug>/',
         views.DeletePageView.as_view(), name='delete-page'),
]

search/urls.py
from django.urls import path

from . import views

app_name = 'search'

urlpatterns = [
    path('', views.search_view, name='search-view'),
    path('tag/<str:tag>/', views.tag_search_view, name='tag-search'),
]

pages/templates/page_detail.html
{% extends 'base.html' %}
{% load filters %}

{% block title %}{{ page.title }} | Pages{% endblock %}

{% block content %}
{% if page.background_image %}
    <div class="page-background mb-2 h-25">
        <img class="rounded w-100 h-100" src="{{ page.background_image.url }}" alt="{{ page.title }}">
    </div>
{% endif %}

<h2>{{ page.title }}</h2>
<p class="text-muted">{{ page.description }}</p>

{% if page.author == user %}
    <h5>
        <a class="badge badge-primary" href="{% url 'pages:update-page' slug=page.slug %}">Update this page</a>
        <a class="badge badge-danger" href="{% url 'pages:delete-page' slug=page.slug %}">Delete this page</a>
    </h5>
{% endif %}

{% if page.author == user %}
    <a class="badge badge-pill badge-primary" href="{% url 'categories:category-detail' slug=page.category.slug %}">
        {{ page.category.name }}
    </a>
{% else %}
    <span class="badge badge-pill badge-primary">{{ page.category.name }}</span>
{% endif %}
<hr>

<div class="page-content">{{ page.content_markup_html | safe }}</div>
<ul class="list-group list-group-horizontal my-3">
    {% for tag in page.tags %}
        <li class="list-group-item">
            <a href="{% url 'search:tag-search' tag=tag %}">{{ tag }}</a>
        </li>
    {% endfor %}
</ul>

<div class="page-details">
    <span class="badge badge-pill badge-primary">{{ page.author.username }}</span>
    <span class="badge badge-pill badge-secondary">{{ page.is_shared | prettify_shared_status }}</span>
    <span class="badge badge-pill badge-secondary">Created: {{ page.date_create }}</span>
    <span class="badge badge-pill badge-secondary">Updated: {{ page.date_update }}</span>
</div>
{% endblock %}