accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('my-profile/',
         views.UserView.as_view(), name='user-profile'),
    path('my-profile/update/',
         views.UpdateUserView.as_view(), name='update-profile'),
    path('my-profile/update/change-password/',
         views.ChangePasswordView.as_view(), name='change-password'),
    path('my-profile/delete/',
         views.DeleteUserView.as_view(), name='delete-profile'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('sign-up/', views.SignUpView.as_view(), name='sign-up'),
]

categories/urls.py
from django.urls import path

from . import views

app_name = 'categories'

urlpatterns = [
    path('category/<slug:slug>/',
         views.CategoryView.as_view(), name='category-detail'),
    path('create/',
         views.CreateCategoryView.as_view(), name='create-category'),
    path('update/<slug:slug>/',
         views.UpdateCategoryView.as_view(), name='update-category'),
    path('delete/<slug:slug>/',
         views.DeleteCategoryView.as_view(), name='delete-category'),
]

knowledge_base/urls.py
from django.urls import path

from . import views

app_name = 'knowledge_base'

urlpatterns = [
    path('', views.HubView.as_view(), name='hub'),
]

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('page/<slug:slug>/', views.PageView.as_view(), name='page-detail'),
    path('shared/<str:username>/<slug:slug>/',
         views.SharedPageView.as_view(), name='shared-page'),
    path('create/', views.CreatePageView.as_view(), name='create-page'),
    path('update/<slug:slug>/',
         views.UpdatePageView.as_view(), name='update-page'),
    path('delete/<slug:slug>/',
         views.DeletePageView.as_view(), name='delete-page'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | My Knowledge Base</title>

    <!--CSS-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!--JavaScript libs-->
    <script src="{% static 'js/jquery-3.5.1.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</head>
<body>
    {% include 'nav.html' %}

    <div class="row my-3 mx-2">
        {% if user.is_authenticated %}
            <div class="col-lg-4">
                {% include 'sidebar.html' with sidebar=True %}
            </div>
        {% endif %}

        <div class="{% if user.is_authenticated %}col-lg{% else %}col-lg-6 mx-auto{% endif %}">
            {% include 'messages.html' %}
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

templates/categories.html
{% load filters %}
<ul class="pl-0 list-group">
    {% if not categories and sidebar %}
        <li class="list-group-item">Empty category list</li>
    {% endif %}

    {% for category in categories %}
        {% with category.category_data as category_object %}
        <li class="list-group-item">
            <h5 class="mt-0">
                <a class="text-body mr-1" href="{% url 'categories:category-detail' slug=category_object.slug %}">
                    {{ category_object.name }}
                </a>

                {% if category.overflow %}
                    <a href="{% url 'categories:category-detail' slug=category_object.slug %}" class="badge badge-light">
                        <span>More pages</span>
                        <span class="badge badge-primary">{{ category.overflow_size }}</span>
                    </a>
                {% endif %}
            </h5>
            <hr>

            {% if not sidebar %}
                <p class="text-muted">{{ category_object.description }}</p>
            {% endif %}

            {% include 'pages.html' with pages=category.recent_pages %}
        </li>
        {% endwith %}
    {% endfor %}
</ul>

templates/confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm delete |{% endblock %}

{% block content %}
<h2>Confirm delete</h2><hr>
<form method="POST">
    {% csrf_token %}
    <button class="btn btn-outline-danger" type="submit">Confirm</button>
</form>
{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1>{{ title }}</h1>
<hr>

<form class="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form.visible_fields %}
        <div class="form-group">
            {% if field.errors %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">{{ field.errors }}</div>
                {% endfor %}
            {% endif %}

            {{ field.label_tag }}

            {% with field.field.widget.input_type as field_type %}
                {% if field_type == 'file' %}
                    {% render_field field class="form-control file-input" %}
                {% elif field_type == 'checkbox' %}
                    {% render_field field %}
                {% else %}
                    {% render_field field class="form-control" %}
                {% endif %}
            {% endwith %}
        </div>
    {% endfor %}
    <button class="btn btn-outline-primary" type="submit">Submit</button>
</form>
{% endblock %}

templates/messages.html
{% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    </div>
{% endif %}

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a href="{% url 'knowledge_base:hub' %}" class="navbar-brand">Hub</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a href="{% url 'accounts:user-profile' %}" class="nav-link">
                    My account 
                    {% if user.is_authenticated %}
                        ({{ user.username }})
                    {% endif %}
                </a>
            </li>
        </ul>
    
        {% if not user.is_authenticated %}
            <ul class="navbar-nav mr-2">
                <li class="nav-item active">
                    <a href="{% url 'accounts:login' %}" class="nav-link">Login</a>
                </li>
                <li class="nav-item active">
                    <a href="{% url 'accounts:sign-up' %}" class="nav-link">Sigh Up</a>
                </li>
            </ul>
        {% endif %}
    
        <form class="form-inline my-2" action="/search/" method="GET">
            <input class="form-control mr-2" type="text" name="q" value="{% if not tag_search %}{{ query_text }}{% endif %}"
                placeholder="Search..." minlength="3" required>
            <button class="btn btn-light my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

templates/pages.html
{% load filters %}
<ul class="list-group">
    {% if not pages %}
        <li class="list-group-item">Empty page list</li>
    {% endif %}

    {% for page in pages %}
        <a class="list-group-item list-group-item-action {% if search and page.author != user %}list-group-item-info{% endif %}" 
            {% if search and page.author != user %}
                href="{% url 'pages:shared-page' username=page.author slug=page.slug %}"
            {% else %}
                href="{% url 'pages:page-detail' slug=page.slug %}"
            {% endif %}>
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ page.title }}</h5>
                <small>{{ page.date_update | prettify_date }}</small>
            </div>

            {% if page.description %}
                <p class="mb-1">{{ page.description }}</p>
            {% endif %}

            {% if not sidebar %}
                {% if search %}
                    <small>{{ page.author }}</small>
                {% endif %}

                <small>{{ page.date_create }}</small>
                <small>{{ page.is_shared | prettify_shared_status }}</small>
                        
                {% if page.tags %}
                    <ul class="list-group list-group-horizontal mt-1">
                        {% for tag in page.tags %}
                            <li class="list-group-item">{{ tag }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endif %}
        </a>
    {% endfor %}
</ul>

templates/sidebar.html
<div class="sidebar">
    {% include 'categories.html' %}
</div>